### ISSUE TITLE
Buguei o joguinho :(

### ISSUE THREAD

**Issue by stormbearx** [pedroevil51/LegionBugs#142]
Estávamos eu e minha namorada jogando as quests iniciais de worgen(já estávamos bem no final mas resolvemos voltar para fazer a quest do gato da vó que tínhamos esquecido)e acabamos caindo na parte imunidada de guilneias,não estávamos conseguindo voltar e tentamos usar a pedra do regresso agora estamos presos na catedral (parte bem do início dos worgens)não conseguimos sair mais de lá

**Comment by stormbearx** [comment]
Nomes dos personagens: Lupina e Lobona

**Comment by klister803** [comment]
Usem a opção de desbugar no site!
