### ISSUE TITLE
Meu personagem esta bugado.

### ISSUE THREAD

**Issue by Berllim** [pedroevil51/LegionBugs#143]
Não estou conseguindo mudar os talentos de skill do meu personagem. 
Personagem: Grim 
![IMG-20200303-WA0021](https://user-images.githubusercontent.com/61422081/75805814-43449380-5d61-11ea-8af1-74814f6a1401.jpg)
![IMG-20200303-WA0022](https://user-images.githubusercontent.com/61422081/75805817-43dd2a00-5d61-11ea-9664-582f62b6ec0a.jpg)

**Comment by klister803** [comment]
Ola amigo, passe para um GM dentro do jogo, ele ira resolver
