### ISSUE TITLE
Quest Bugada - Golens aos Pedaços [Burning Steppes]

### ISSUE THREAD

**Issue by Pyriclock** [pedroevil51/LegionBugs#152]
O NPC da quest não dropa os itens para completá-la. Verifiquei no WoWHead antes de abrir o ticket. Segue print para visualização:

![image](https://user-images.githubusercontent.com/59344512/76822087-c7c9f400-67ee-11ea-9168-c338e8901c08.png)

**Comment by klister803** [comment]
por favor essa quest foi modifica para o server, delete sua pasta cache e tente novamente
