### ISSUE TITLE
bug do cliente do site 

### ISSUE THREAD

**Issue by faizerOpaladino** [pedroevil51/LegionBugs#21]
o cliente nao abre  ( versao 32/64 bits )

**Comment by MatheusSBranco** [comment]
Tenta altera a pasta Data para não deixar apenas leitura, aí vc tenta e ele n vai abrir, então vc tira pelo gerenciador de tarefas e abre de novo. No meu caso prefiro baixar a versão completa que não tem essa frescura e também porque não no completo não deu erro de conexão.
