### ISSUE TITLE
BUG - QUEST "O chamado da coroa de gelo"

### ISSUE THREAD

**Issue by Pintodamorte** [pedroevil51/LegionBugs#32]
Simplesmente fica nessa tela preta eternamente obrigado eu a apertar Alt + F4
E quando eu volto ao jogo não da pra completar a quest porque os "Estágios" saiem.

https://www.youtube.com/watch?v=9SXJpxMjJKQ

**Comment by klister803** [comment]
Você usa o jogo completo? eu fiz o teste aqui e funcionou normalmente

**Comment by klister803** [comment]
Já fazem 5 dias que não houve uma atualização @Pintodamorte , caso você ainda esteja com o problema re-abra o ticket
