### ISSUE TITLE
Bug World Quest - Val'Sharah

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#34]
O boss Ealdis da World quest de Val'Sharah não está spwanando.

**Comment by klister803** [comment]
![image](https://user-images.githubusercontent.com/35279034/69721797-6291ac00-10f4-11ea-8c8f-864ca4d06cf8.png)
Por favor procure neste lugar

**Comment by MatheusSBranco** [comment]
Apareceu.
