### ISSUE TITLE
Bug Visual de Membro de Party

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#35]
As vezes a pessoa da party não aparece para ninguém dentro ou fora da dg até todo mundo relogar ou refazer a party; e depois que o membro de distância alguns metros, se torna incapaz de saber onde ele está, porque sua posição não muda no mininapa e também ocorre de vez em quando que o membro está desconectado quando não está.

**Comment by klister803** [comment]
Resolvido, aumentando a visibilidade dos jogadores
