### ISSUE TITLE
Bug Quests

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#38]
Ajuda às linhas de frente - mesmo curando todos, não está contando a quest, que é curar os defensores feridos.

Destino não cumprido - era pra quando eu chegasse no Black Temple aparecer em cima da barra de skill uma skill para usar e iniciar um cenário.

**Comment by klister803** [comment]
Por favor testar novamente

**Comment by MatheusSBranco** [comment]
Ok

**Comment by MatheusSBranco** [comment]
As duas se auto completaram.
