### ISSUE TITLE
Bug no cenário da Costas Partidas

### ISSUE THREAD

**Issue by Kaerne** [pedroevil51/LegionBugs#43]
Estava fazendo o cenário da Costas Partidas de boa, até que cheguei na parte da nave, nessa parte eu tenho que armar 7 bombas, porém na nave só tinha 5, andei a nave toda e nada, até que notei que eu estava sendo atordoado as vezes e estava tomando dmg, estranhei pois tinha limpado todos os mobs da nave e percebi que tinha uma habilidade sendo castada em mim por algum mob invisível (Provavelmente o mesmo estava me atacando e aturdindo) e se pá era matando esse mob que eu liberaria algum acesso as bombas restantes.
Meu nick está na print (Kaeerne).
![image](https://user-images.githubusercontent.com/57514330/69916410-74978580-1439-11ea-855e-eb0541c09d2e.png)

**Comment by MatheusSBranco** [comment]
As 2 bombas estavam logo no início.

**Comment by klister803** [comment]
Testei e completei normalmente, caso esteja com esse mesmo problema por favor re-abra com um video mostrando o problema ou print
