### ISSUE TITLE
Bug Quest-> Missão: Portais Murketh e Shaadraz

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#46]
A quest pede para que a gente fale com o npc "Comandante de Ala Brack" para que ele faça a gente montar na montaria automática e destroir os portais, mas quando tento falar com ele, simplesmente sou teleportado um pouco para trás. (Mas dá para ir a pé, jogar a bomba e completar a quest)

Missão: https://pt.wowhead.com/quest=10129/miss%C3%A3o-portais-murketh-e-shaadraz

NPC: https://pt.wowhead.com/npc=19401/comandante-de-ala-brack

**Comment by klister803** [comment]
Esse problema é existente somente no beta, enquanto as rotas de voo estão setadas para serem completadas instantaneamente .
