### ISSUE TITLE
Bug Quets - Um guia espiritual

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#47]
O bug é que eu não consigo completar a quest com o NPC "Gorkan Punho de Sangue", porque não aparece nenhuma janela de diálogo quando clico nele. 
https://pt.wowhead.com/quest=9410/um-guia-espiritual
https://pt.wowhead.com/npc=16845/gorkan-punho-de-sangue

**Comment by klister803** [comment]
Completavel
