### ISSUE TITLE
Quest bugada "Escolta para a caravana da Encruzilhada"

### ISSUE THREAD

**Issue by Kaerne** [pedroevil51/LegionBugs#48]
A quest pede para que a gente fale com um npc para escoltar uma caravana, mas ao falar com o npc não há nenhuma interação para começar a escolta.
![image](https://user-images.githubusercontent.com/57514330/70374117-33d2bd00-18ce-11ea-88ac-860a8a6039b2.png)
![image](https://user-images.githubusercontent.com/57514330/70374120-3a613480-18ce-11ea-9f0a-492c59b9a875.png)

**Comment by klister803** [comment]
Completavel
