### ISSUE TITLE
Bug Quest - O negro coração das chamas : Monte Hyjal

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#49]
A quest pede para invocar o mob na área "Inferno", mas essa área já está sendo "O Recrescer" que é uma área que aparece depois de completar as quests de história em Hyjal, então não dá para invocar o mob.

https://pt.wowhead.com/quest=25428/o-negro-cora%C3%A7%C3%A3o-das-chamas

**Comment by klister803** [comment]
Fixada
