### ISSUE TITLE
Quest Bug - A ronda

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#50]
Ele pede para eu prestar continência para os Patruoheiros Renegados, eu sai saudando geral no navio e a quest não contou.

https://pt.wowhead.com/quest=39698/a-ronda

https://youtu.be/4zSObyZj-7U

**Comment by klister803** [comment]
Eu tinha mexido nessa quest, você pode re-testar? e se ela ainda estiver bugada re-abra o ticket
