### ISSUE TITLE
Bug Quest - Legado dos Cristacorvo

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#51]
Ele pede para ir num específico no Castelo Corvo Negro em Val'Sharah para ali iniciar um cenário, só que não aparece aquela skill de quest em cima da barra de habilidades para iniciar o cenário. Só botei o link do vídeo para ver o que falei.

https://pt.wowhead.com/quest=44479/legado-dos-cristacorvo
https://youtu.be/DuJ7fIzqaJk

**Comment by klister803** [comment]
Completavel
