### ISSUE TITLE
Quests Bugadas

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#52]
O teste de Havi:
Ele pede para adicionar os itens, mas quando tento, subo em cima de um coelho que não possui nenhuna skill.

https://pt.wowhead.com/quest=38331/o-teste-de-havi

À prova de arpoadas:
A quest pede para destruir os lançadores de arpões, mas quando clico pra destruir a quest não conta.

https://pt.wowhead.com/quest=38615/%C3%A0-prova-de-arpoadas

**Comment by klister803** [comment]
![image](https://user-images.githubusercontent.com/35279034/71633087-f0c7e900-2bf0-11ea-9b8d-26fe3a0c657b.png)
Quest Teste de Havi Fixada
Todo: A prova de Arpoadas

**Comment by klister803** [comment]
As duas quest estão funcionando, agradeço o report.
