### ISSUE TITLE
Quest Bug - Trilhando os mesmos passos : Alta Montanha

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#55]
No início da quest ele pede para eu usar a Água da Visão para poder me transformar no Drogbar Mordepedra e matar uns bichos e pôr a proteção de Mordepedra, mas quando me transformo não existe nenhuma skill para ser utilizada para poder matar os bichos.

https://pt.wowhead.com/quest=41764/trilhando-os-mesmos-passos

**Comment by klister803** [comment]
![image](https://user-images.githubusercontent.com/35279034/72749707-8d026180-3b99-11ea-8549-88cf8fd09724.png)
Bug fixado, obrigado pelo report
