### ISSUE TITLE
NPCs multiplicados

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#58]
Os seguintes NPC's e mob estão multiplicados no Castelo Corvo Negro no Umbrocharco:

Asha Corvocanto: https://pt.wowhead.com/npc=94975/asha-corvocanto
Sirius Ebanasa: https://pt.wowhead.com/npc=94974/sirius-ebanasa
Maiev Cantonegro: https://pt.wowhead.com/npc=92987/maiev-cantonegro
Tenente Desdel Olhestela: https://pt.wowhead.com/npc=93031/tenente-desdel-olhestela

E eles fazem parte das seguintes quest:
https://pt.wowhead.com/quest=38719/liberdade-aos-illidari
https://pt.wowhead.com/quest=38724/amor-fraternal
https://pt.wowhead.com/quest=38721/o-tenente-da-torre

Isso não impede de completar a quest, mas no caso do elite meio que o torne impossível com tanto elite te batendo. Acho que há essa multiplicação, porque há uma diferenciação dessa quest para o Demon Hunter.

**Comment by klister803** [comment]
Favor testar novamente a area
Caso ainda esteja bugado re-abre o ticket
