### ISSUE TITLE
Bug Quest - AHHHHHHHHHHHH! AHHHHHHHHH!!!

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#59]
A quest pede para eu entrar no tanque para matar 200 orcs, mas não aparece o simbolo do mouse para que eu possa subir no tanque.

https://www.wowhead.com/quest=26708/ahhhhhhhhhhhh-ahhhhhhhhh

**Comment by klister803** [comment]
Quest auto-completa até ser fixada futuramente.
