### ISSUE TITLE
World Quest Bug - Beemotes adormecidos : Ermos Antoranos

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#61]
A world quest é basicamente a gente clicar nos demônios para eles saírem do estado e êxtase e nos enfrentar e matarmos eles, mas o único que não sai desse estado é o Radix, não importa quantas vezes a gente já tenha relogado ou deixado para fazer depois, ele não vem bater na gente.

https://pt.wowhead.com/quest=48514/beemotes-adormecidos

**Comment by klister803** [comment]
Fixada
