### ISSUE TITLE
Quest Bug - Ver raptor : Selva do Espinhaço Setentrional

### ISSUE THREAD

**Issue by MatheusSBranco** [pedroevil51/LegionBugs#62]
A quest pede para eu falar com a NPC Sacerdotisa Thaalia quando eu estiver pronto, mas não aparece a opção para confirmar a minha prontidão.

https://www.wowhead.com/quest=26773/see-raptor
https://www.wowhead.com/npc=44017/priestess-thaalia

![image](https://user-images.githubusercontent.com/28764084/71648266-50052680-2ce1-11ea-9680-713493490586.png)

**Comment by klister803** [comment]
Auto completavel até ser fixada futuramente
