### ISSUE TITLE
Mob em Trommheim

### ISSUE THREAD

**Issue by Ycero** [pedroevil51/LegionBugs#64]
pra baixo de hrydshal tem um mob com o nome de Carrasco Vilscarnio que conta como dois na quest e quando voce mata ele, ele respawna depois de 3 segundos e na mesma regiao o mob Subjugador Viscarnio nao te ataca enquanto voce mata ele.

**Comment by klister803** [comment]
Carrasco Vilscarnio Fixado 
Não consegui achar o outro mob, esse nome está correto? não acho em algum lugar
