### ISSUE TITLE
Quest bugada

### ISSUE THREAD

**Issue by Pyriclock** [pedroevil51/LegionBugs#66]
A quest "Sabotar o Portal", em Eternévoa (Netherstorm pra quem joga em inglês) não se completa. Após escoltar o NPC para destruir o portal, ele pede pra falar com outro NPC para entregar a quest, e, de acordo com o Wowhead (e o vídeo do Gitgubguides), nesse momento a quest se completa. Estou mandando algumas fotos, a primeira é o NPC que dá a missão. A segunda é a localização desse NPC, a terceira é a fala dele mostrando q completei a missão e a quarta é eu tentando entregar a quest.
![Sem título 2](https://user-images.githubusercontent.com/59344512/71776146-30812e80-2f6b-11ea-8bc1-31214519c5ba.png)
![Sem título 3](https://user-images.githubusercontent.com/59344512/71776147-337c1f00-2f6b-11ea-8f7d-4402eac6fae0.png)
![Sem título 4](https://user-images.githubusercontent.com/59344512/71776148-35de7900-2f6b-11ea-9c10-833647bf2cd6.png)
![Sem título 5](https://user-images.githubusercontent.com/59344512/71776150-3840d300-2f6b-11ea-9a59-24a95d6a1542.png)

**Comment by klister803** [comment]
cancela e pega dnv
