### ISSUE TITLE
Reportar bug

### ISSUE THREAD

**Issue by Jjosue124** [pedroevil51/LegionBugs#67]
![15783208862961440661101636805032](https://user-images.githubusercontent.com/59568904/71824171-abd00680-3077-11ea-80be-b1f2c1a6b666.jpg)
Essas 2 quests de val'sharah

A primeira a tyrande n tem a opção de ready.
A segunda n tem como entregar.

**Comment by klister803** [comment]
Close enough to touch - fixada 
Por favor cancele e pegue a quest novamente

**Comment by klister803** [comment]
Sobre a the Corruptor, consegui entregar normalmente.
