### ISSUE TITLE
Bug de inventário e Montaria promocional

### ISSUE THREAD

**Issue by Khrizalid** [pedroevil51/LegionBugs#80]
Boa Tarde, seguem abaixo dois bugs:

1 - O organizador automatico do inventário não está funcionando

2 - A montaria promocional, não incluiram o warrior pra utilizar, quando peguei eu era warrior nao posso usar, todas as classes estao la menos essa, esta correto?

**Comment by klister803** [comment]
2 - Foi resolvido, sobre o organizador, estamos deixando ele por ultimo
