### ISSUE TITLE
Habilidade [Deslocamento] bugada.

### ISSUE THREAD

**Issue by Dvassoavik** [pedroevil51/LegionBugs#85]
Habilidade [Deslocamento] (Mage) não funciona.
-

"Teleporta você de volta para onde usou Lampejo pela última vez e conclui a recarga de Lampejo. Só pode ser usado dentro de 10 sec após Lampejo."

**Comment by klister803** [comment]
Pode explicar direito, eu consigo utilizar normalmente

**Comment by baeoeab** [comment]
Também me parece que está funcionando perfeitamente

**Comment by klister803** [comment]
Como não houve resposta em mais de 5 dias, vou fechar o post
