### ISSUE TITLE
Interações relacionadas a 2 quests bugadas [Uma pedra de Sangue e O mistério de Dreyrgrot] - Trommheim

### ISSUE THREAD

**Issue by WeekendWarrior00** [pedroevil51/LegionBugs#90]
As 2 quests ocorrem na mesma região e tem a ver com barcos piratas na região.
https://pt.wowhead.com/quest=42635/o-mist%C3%A9rio-de-dreyrgrot
https://pt.wowhead.com/quest=42639/uma-pedra-de-sangue

O bug em si é que existem cordas para subir nos barcos e ao clicar neles não acontece nada...

**Comment by klister803** [comment]
Fixado
